{% set name = "dash-extensions" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_extensions-{{ version }}.tar.gz
  sha256: cec84f601c39a47b7a01686be3e2227f0e7e8bbe79466f4f6fb01f36d71a351a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1

  run:
    - python >=3.7
    - dash >=2.7
    - flask-caching =2.0.1
    - jsbeautifier >=1.14.3,<2
    - more-itertools >=8.12.0,<9


test:
  imports:
    - dash_extensions
  # failing due to dash missing dash-core-components, dash-html-components and dash-table 
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/thedirtyfew/dash-extensions/
  summary: Extensions for Plotly Dash.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - whophil
    - mitchellwood
    - fhoehle
