{% set name = "dash-extensions" %}
{% set version = "0.0.67" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash-extensions-{{ version }}.tar.gz
  sha256: 932ff679467d1611f024dc476fdeda2c7b5bf4f52bff9788e5f2759b1adc592d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dash
    - jsbeautifier
    - flask-caching
    - more-itertools
    - python >=3.6

test:
  imports:
    - dash_extensions
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/thedirtyfew/dash-extensions/
  summary: Extensions for Plotly Dash.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mitchellwood
